services:
#  caddy:
#    image: caddy:latest
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./Caddyfile:/etc/caddy/Caddyfile
#      - ./:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./index.php:/var/www/index.php
  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "9000:9000"
    environment:
      NEWRELIC_ENABLED: true

